// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEExot6rRv8SzxTPXUnvvsgP_mtAeCzig',
    appId: '1:1053291846689:web:0a71bbfc38f9a1812dd760',
    messagingSenderId: '1053291846689',
    projectId: 'fasum-d89ca',
    authDomain: 'fasum-d89ca.firebaseapp.com',
    storageBucket: 'fasum-d89ca.firebasestorage.app',
    measurementId: 'G-31M7GD6QF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxdvTfSsFdluc35TuDK9eNCRY9fxJ-5k',
    appId: '1:1053291846689:android:ec8a3cd78ff84e402dd760',
    messagingSenderId: '1053291846689',
    projectId: 'fasum-d89ca',
    storageBucket: 'fasum-d89ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwydncQR9LR08SRVAZDmSJ1Sv4eCuh_M',
    appId: '1:1053291846689:ios:9951d6681596fdb02dd760',
    messagingSenderId: '1053291846689',
    projectId: 'fasum-d89ca',
    storageBucket: 'fasum-d89ca.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwydncQR9LR08SRVAZDmSJ1Sv4eCuh_M',
    appId: '1:1053291846689:ios:9951d6681596fdb02dd760',
    messagingSenderId: '1053291846689',
    projectId: 'fasum-d89ca',
    storageBucket: 'fasum-d89ca.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEExot6rRv8SzxTPXUnvvsgP_mtAeCzig',
    appId: '1:1053291846689:web:544cc5e2ee2d6e102dd760',
    messagingSenderId: '1053291846689',
    projectId: 'fasum-d89ca',
    authDomain: 'fasum-d89ca.firebaseapp.com',
    storageBucket: 'fasum-d89ca.firebasestorage.app',
    measurementId: 'G-VHHHYW5NZV',
  );
}
